name: ensemble
description: Ensemble Runtime

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+5

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: '3.19.3'

dependencies:
  flutter:
    sdk: flutter

  device_preview:
    git:
      url: https://github.com/EnsembleUI/flutter_device_preview.git
      ref: develop
      path: device_preview

  yaml: ^3.1.2
  intl: ^0.18.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  flutter_rating_bar: ^4.0.0
  fl_chart: ^0.62.0
  signature: ^5.2.1

  ensemble_icons:
    git:
      url: https://github.com/EnsembleUI/ensemble_icons.git
      ref: main

  ensemble_ts_interpreter:
    git:
      url: https://github.com/EnsembleUI/ensemble_ts_interpreter.git
      ref: master

  ensemble_bracket:
    git:
      url: https://github.com/EnsembleUI/ensemble_bracket.git
      ref: main
  # use our forked high_chart to fix iOS issue
  high_chart:
    git: https://github.com/EnsembleUI/high_chart.git
  event_bus: ^2.0.0
  flutter_layout_grid: ^2.0.3
  email_validator: ^2.0.1
  mask_text_input_formatter: ^2.5.0
  otp_pin_field:
    git:
      url: https://github.com/EnsembleUI/otp_pin_field.git
      ref: develop
  form_validator: ^2.1.1
  flutter_svg: ^2.0.7
  flutter_svg_provider: ^1.0.4
  qr_flutter: ^4.1.0
  device_info_plus: ^9.1.2
  carousel_slider: ^4.1.1
  fluttertoast: 8.2.2
  video_player: ^2.6.1
  lottie: ^2.3.2
  js_widget:
    git: https://github.com/EnsembleUI/js_widget.git
  flutter_markdown: ^0.6.10+5
  url_launcher: ^6.1.11
  provider: ^6.0.3
  cloud_firestore: ^4.14.0
  get_storage: ^2.0.3
  flutter_html: ^3.0.0-beta.1 # flutter_html ^2.0.0 requires flutter_svg <1.0.0, conflicts with ours
  webview_flutter: ^4.2.0
  cached_network_image: ^3.2.3
  sensors_plus: ^3.0.0
  mime: ^1.0.4
  flutter_cache_manager: ^3.3.0
  google_fonts: ^4.0.3
  walletconnect_dart: ^0.0.11
  http_parser: ^4.0.2
  shared_preferences: ^2.1.1
  workmanager: ^0.5.1
  flutter_local_notifications: ^16.1.0
  flutter_i18n: ^0.33.0
  pointer_interceptor: ^0.9.3+4
  flutter_secure_storage: ^8.1.0
  staggered_grid_view_flutter: ^0.0.4
  dart_jsonwebtoken: ^2.8.2
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.0
  custom_image_crop: ^0.0.10
  app_settings: ^5.0.0
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  custom_refresh_indicator: ^2.2.1
  youtube_player_iframe: ^4.0.4
  web_socket_client: ^0.1.0
  app_links: ^3.4.3
  share_plus: ^7.2.2
  rate_my_app: ^2.0.0
  table_calendar:
    git:
      url: https://github.com/EnsembleUI/table_calendar
      ref: master

  flutter_app_badger: ^1.5.0
  webview_flutter_wkwebview: ^3.9.2
  webview_flutter_android: ^3.12.0

  receive_sharing_intent: 1.6.7
  change_case: ^1.1.0
  dropdown_button2: ^2.3.9
  collection: ^1.17.1
  package_info_plus: ^3.1.2
  audioplayers: ^5.2.1
  logger: ^2.2.0
  visibility_detector: ^0.4.0+2
  local_auth: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.1.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

    # integration tests (TODO - exclude from build)
    - integration_test/local/defaultApp/
    - integration_test/local/themedApp/
    - integration_test/local/dialogsAndToast/

  fonts:
    # icon fonts
    - family: Remix
      fonts:
        - asset: assets/iconFonts/remixicon.ttf

    # semi-custom fonts
    - family: idealTalent
      fonts:
        - asset: assets/fonts/idealTalent/icomoon.ttf
    - family: Clarika
      fonts:
        - asset: assets/fonts/idealTalent/Clarika.ttf
    - family: ClarikaRegular
      fonts:
        - asset: assets/fonts/idealTalent/ClarikaRegular.ttf

    # other fonts available to apps
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-VariableFont_wght.ttf
        - asset: assets/fonts/Jost-Italic-VariableFont_wght.ttf
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - weight: 500
          asset: assets/fonts/inter/Inter-Medium.ttf
        - weight: 600
          asset: assets/fonts/inter/Inter-SemiBold.ttf
        - weight: 700
          asset: assets/fonts/inter/Inter-Bold.ttf
        - weight: 800
          asset: assets/fonts/inter/Inter-ExtraBold.ttf

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.ensembleui.ensemble
    iosBundleIdentifier: com.ensembleui.ensemble