name: ensemble
description: Ensemble Runtime

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+5

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^3.1.0
  font_awesome_flutter: 9.2.0
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_rating_bar: ^4.0.0
  fl_chart: ^0.55.0
  signature: ^5.2.1

  ensemble_ts_interpreter:
    git:
      url: https://github.com/EnsembleUI/ensemble_ts_interpreter.git
      ref: master

  # use our forked high_chart to fix iOS issue
  high_chart:
    git: https://github.com/EnsembleUI/high_chart.git
  event_bus: ^2.0.0
  mockito: ^5.1.0
  flutter_layout_grid: ^2.0.0
  flutter_i18n:
    git:
      url: https://github.com/ilteoood/flutter_i18n.git
      ref: master
  email_validator: ^2.0.1
  form_validator: ^1.0.2
  flutter_svg: ^1.1.0
  qr_flutter: ^4.0.0
  device_info_plus: ^4.0.2
  flutter_map: ^2.0.0
  carousel_slider: ^4.1.1
  fluttertoast: ^8.0.9
  video_player: ^2.4.5
  lottie: ^1.4.1
  js_widget:
    git: https://github.com/EnsembleUI/js_widget.git
  flutter_markdown: ^0.6.10+5
  url_launcher: ^6.1.5
  provider: ^6.0.3
  cloud_firestore: 4.4.0
  geolocator: ^9.0.2
  get_storage: ^2.0.3
  flutter_html: ^3.0.0-alpha.6    # flutter_html ^2.0.0 requires flutter_svg <1.0.0, conflicts with ours
  camera: ^0.10.3
  image_picker: ^0.8.6
  webview_flutter: ^4.0.1
  file_picker: ^5.2.5
  cached_network_image: ^3.2.3
  sensors_plus: ^2.0.2
  mime: ^1.0.4
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

    # integration tests (TODO - exclude from build)
    - ensemble/integration_tests/
    - ensemble/integration_tests/defaultApp/
    - ensemble/integration_tests/themedApp/

  fonts:
    # semi-custom fonts
    - family: idealTalent
      fonts:
        - asset: assets/fonts/idealTalent/icomoon.ttf
    - family: Clarika
      fonts:
        - asset: assets/fonts/idealTalent/Clarika.ttf
    - family: ClarikaRegular
      fonts:
        - asset: assets/fonts/idealTalent/ClarikaRegular.ttf

    # other fonts available to apps
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-VariableFont_wght.ttf
        - asset: assets/fonts/Jost-Italic-VariableFont_wght.ttf
          style: italic


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.ensembleui.ensemble
    iosBundleIdentifier: com.ensembleui.ensemble
