name: ensemble_bracket
description: "A package for elimination style tournament brackets in ensemble"
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ensemble:
    path: ../ensemble
#    git:
#      url: https://github.com/EnsembleUI/ensemble.git
#      ref: main
#      path: modules/ensemble

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

